const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const csvParser = require('csv-parser');
const Student = require('../models/Student');

const MASTER_CSV_PATH = path.join(__dirname, '..', '..', 'output', 'master_performance.csv');
const RANKINGS_CSV_PATH = path.join(__dirname, '..', '..', 'output', 'final_rankings.csv');
const SUMMARY_CSV_PATH = path.join(__dirname, '..', '..', 'output', 'module_summary.csv');

// Helper function to check if server is in database mode
const isDbConnected = () => {
  return global.dbConnected === true;
};

// Helper: Parse CSV file into an array of objects
const parseCSV = (filePath) => {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(filePath)) {
      return resolve([]);
    }
    const results = [];
    fs.createReadStream(filePath)
      .pipe(csvParser())
      .on('data', (data) => results.push(data))
      .on('end', () => resolve(results))
      .on('error', (err) => reject(err));
  });
};

// Route 1: Get all students leaderboard
router.get('/', async (req, res) => {
  try {
    if (isDbConnected()) {
      const students = await Student.find().sort({ rank: 1 });
      return res.json(students);
    } else {
      const data = await parseCSV(RANKINGS_CSV_PATH);
      const formatted = data.map((row) => ({
        name: row.Name,
        email: row.Email,
        cumulativeScore: parseFloat(row.Cumulative_Score),
        cumulativeMax: parseFloat(row.Cumulative_Max),
        cumulativePct: parseFloat(row.Cumulative_Pct),
        finalPercentile: parseFloat(row.Final_Percentile),
        rank: parseInt(row.Rank, 10),
        grade: row.Grade,
      }));
      return res.json(formatted);
    }
  } catch (err) {
    console.error('Error fetching students:', err);
    return res.status(500).json({ error: 'Server error fetching student list' });
  }
});

// Route 2: Get analytics & summary statistics
router.get('/stats', async (req, res) => {
  try {
    let students = [];
    let summaryData = [];

    if (isDbConnected()) {
      students = await Student.find();
      // We will parse the summary CSV for module averages since it's already generated by python
      summaryData = await parseCSV(SUMMARY_CSV_PATH);
    } else {
      students = await parseCSV(RANKINGS_CSV_PATH);
      summaryData = await parseCSV(SUMMARY_CSV_PATH);
    }

    if (students.length === 0) {
      return res.json({
        totalStudents: 0,
        avgPercentage: 0,
        highestPercentage: 0,
        passRate: 0,
        gradeCounts: {},
        moduleAverages: []
      });
    }

    // Calculations
    const totalStudents = students.length;
    let pctSum = 0;
    let highestPct = -1;
    let lowestPct = 101;
    let highestScorer = null;
    let lowestScorer = null;
    let passingCount = 0;
    const gradeCounts = {};

    students.forEach((s) => {
      const name = isDbConnected() ? s.name : s.Name;
      const email = isDbConnected() ? s.email : s.Email;
      const rank = parseInt(isDbConnected() ? s.rank : s.Rank, 10);
      const pct = parseFloat(isDbConnected() ? s.cumulativePct : s.Cumulative_Pct);
      const grade = isDbConnected() ? s.grade : s.Grade;

      pctSum += pct;
      if (pct > highestPct) {
        highestPct = pct;
        highestScorer = { name, email, cumulativePct: pct, grade, rank };
      }
      if (pct < lowestPct) {
        lowestPct = pct;
        lowestScorer = { name, email, cumulativePct: pct, grade, rank };
      }
      if (grade !== 'F') passingCount++;
      
      gradeCounts[grade] = (gradeCounts[grade] || 0) + 1;
    });

    const avgPercentage = pctSum / totalStudents;
    const passRate = (passingCount / totalStudents) * 100;

    const moduleAverages = summaryData.map((row) => ({
      name: row['Module Name'],
      avgPct: parseFloat(row['Average Percentage'])
    }));

    let totalQuizzes = 0;
    let recentUploads = [];
    try {
      const quizzesDir = path.join(__dirname, '..', '..', 'quizzes');
      if (fs.existsSync(quizzesDir)) {
        const files = fs.readdirSync(quizzesDir).filter(f => f.endsWith('.csv'));
        totalQuizzes = files.length;
        recentUploads = files.map(file => {
          const fileStats = fs.statSync(path.join(quizzesDir, file));
          const d = fileStats.mtime;
          const pad = n => String(n).padStart(2, '0');
          const dateStr = `${pad(d.getDate())}/${pad(d.getMonth() + 1)}/${d.getFullYear()}, ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
          return { filename: file, dateStr, mtime: fileStats.mtime };
        }).sort((a, b) => b.mtime - a.mtime)
          .map(f => ({ filename: f.filename, dateStr: f.dateStr }));
      }
    } catch (e) {
      console.error('Error reading quizzes dir for stats:', e);
    }

    return res.json({
      totalStudents,
      avgPercentage,
      highestPercentage: highestPct,
      passRate,
      gradeCounts,
      moduleAverages,
      highestScorer,
      lowestScorer,
      totalQuizzes,
      recentUploads
    });
  } catch (err) {
    console.error('Error fetching statistics:', err);
    return res.status(500).json({ error: 'Server error fetching statistics' });
  }
});

// Route 3: Get remedial students list
router.get('/remedial', async (req, res) => {
  try {
    if (isDbConnected()) {
      const students = await Student.find({
        $or: [
          { cumulativePct: { $lt: 50 } },
          { grade: { $in: ['D', 'F'] } }
        ]
      }).sort({ rank: 1 });
      return res.json(students);
    } else {
      const data = await parseCSV(RANKINGS_CSV_PATH);
      const filtered = data
        .filter((row) => {
          const pct = parseFloat(row.Cumulative_Pct);
          const grade = row.Grade;
          return pct < 50 || grade === 'D' || grade === 'F';
        })
        .map((row) => ({
          name: row.Name,
          email: row.Email,
          cumulativePct: parseFloat(row.Cumulative_Pct),
          grade: row.Grade,
          rank: parseInt(row.Rank, 10)
        }));
      return res.json(filtered);
    }
  } catch (err) {
    console.error('Error fetching remedial list:', err);
    return res.status(500).json({ error: 'Server error fetching remedial list' });
  }
});

// Route 4: Get individual student lookup profiles (quizzes & modules)
router.get('/profile/:email', async (req, res) => {
  const { email } = req.params;
  try {
    if (isDbConnected()) {
      const student = await Student.findOne({ email: email.toLowerCase() });
      if (!student) {
        return res.status(404).json({ error: 'Student profile not found' });
      }
      return res.json(student);
    } else {
      // Find details from master CSV
      const masterData = await parseCSV(MASTER_CSV_PATH);
      const studentRow = masterData.find(row => row.Email.toLowerCase() === email.toLowerCase());
      
      if (!studentRow) {
        return res.status(404).json({ error: 'Student profile not found' });
      }

      // Reconstruct dynamic data from CSV row
      const quizScores = {};
      const quizPercentages = {};
      const moduleScores = {};
      const modulePercentages = {};
      const modulePercentiles = {};

      Object.keys(studentRow).forEach(key => {
        // Quiz formats: dayX_moduleY_quizZ
        if (key.startsWith('day')) {
          if (key.endsWith('_pct')) {
            quizPercentages[key] = parseFloat(studentRow[key]);
          } else {
            quizScores[key] = parseFloat(studentRow[key]);
          }
        }
        // Module formats: Module X...
        else if (key.startsWith('Module')) {
          if (key.endsWith('_score')) {
            const modName = key.replace('_score', '');
            moduleScores[modName] = parseFloat(studentRow[key]);
          } else if (key.endsWith('_pct')) {
            const modName = key.replace('_pct', '');
            modulePercentages[modName] = parseFloat(studentRow[key]);
          } else if (key.endsWith('_percentile')) {
            const modName = key.replace('_percentile', '');
            modulePercentiles[modName] = parseFloat(studentRow[key]);
          }
        }
      });

      // Look up if ML predictions are available in the master CSV
      // If we read master CSV, check if ML predicted columns are appended
      // Wait! Let's ensure the profile lookup includes predictedScore/predictedGrade if available
      // In python we didn't write ML outputs to CSV; they are saved to joblib model files.
      // So the backend can dynamically run ML predictions, or read them if we write a helper.
      // Let's implement reading ML files in the backend as well, or serving them directly.
      // Let's check: can we load pickle files in Node? No, pickle is python-specific.
      // But we can check if they exist, or we can just compute the ML predictions in Node!
      // Wait, let's keep it simple: we can read the python model results or just write a small prediction logic in Node by reading the saved models. Or, we can just load the predictions from a json or directly output them. 
      // Actually, an even easier way is: we can train the models in python, and save the predictions for ALL students in a JSON file `output/predictions.json` during training, and then the Node.js backend can easily read this JSON file!
      // This is an incredibly smart, clean, cross-language bridge!
      // Let's modify `src/train_model.py` to write predictions for all students to `output/predictions.json`!
      // That way, both MongoDB and CSV modes in Node.js can instantly fetch the predictions without executing python models in Node!
      // Let's verify this design: it's extremely clean. Let's write the routing code assuming `predictions.json` might exist.

      const predictionsPath = path.join(__dirname, '..', '..', 'output', 'predictions.json');
      let predictedScore = null;
      let predictedGrade = null;

      if (fs.existsSync(predictionsPath)) {
        try {
          const preds = JSON.parse(fs.readFileSync(predictionsPath, 'utf8'));
          if (preds[email.toLowerCase()]) {
            predictedScore = preds[email.toLowerCase()].predictedScore;
            predictedGrade = preds[email.toLowerCase()].predictedGrade;
          }
        } catch (e) {
          console.error("Error reading predictions JSON:", e);
        }
      }

      const formatted = {
        name: studentRow.Name,
        email: studentRow.Email,
        cumulativeScore: parseFloat(studentRow.Cumulative_Score),
        cumulativeMax: parseFloat(studentRow.Cumulative_Max),
        cumulativePct: parseFloat(studentRow.Cumulative_Pct),
        finalPercentile: parseFloat(studentRow.Final_Percentile),
        rank: parseInt(studentRow.Rank, 10),
        grade: studentRow.Grade,
        quizScores,
        quizPercentages,
        moduleScores,
        modulePercentages,
        modulePercentiles,
        predictedScore,
        predictedGrade
      };
      
      return res.json(formatted);
    }
  } catch (err) {
    console.error('Error fetching student profile:', err);
    return res.status(500).json({ error: 'Server error fetching student profile' });
  }
});

module.exports = router;
