import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv
import config_loader

# Load .env from project root
load_dotenv(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '.env')))

OUTPUT_EMAILS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'output', 'emails_sent'))

def _get_email_settings():
    """Get email settings with .env overriding config.json values."""
    config = config_loader.load_config()
    settings = config_loader.get_email_settings(config)
    
    # .env variables take priority over config.json
    if os.getenv('SMTP_SERVER'):
        settings['smtp_server'] = os.getenv('SMTP_SERVER')
    if os.getenv('SMTP_PORT'):
        settings['smtp_port'] = int(os.getenv('SMTP_PORT'))
    if os.getenv('SENDER_EMAIL'):
        settings['sender_email'] = os.getenv('SENDER_EMAIL')
    if os.getenv('SENDER_PASSWORD'):
        settings['sender_password'] = os.getenv('SENDER_PASSWORD')
    if os.getenv('USE_TLS'):
        settings['use_tls'] = os.getenv('USE_TLS', 'true').lower() == 'true'
    if os.getenv('MOCK_MODE'):
        settings['mock_mode'] = os.getenv('MOCK_MODE', 'false').lower() == 'true'
    
    return settings

def send_performance_email(student_name, student_email, grade_card_path, overall_pct, grade, rank):
    """Sends the performance report card to a student.
    Uses mock mode or real SMTP based on configuration.
    """
    email_settings = _get_email_settings()
    mock_mode = email_settings.get("mock_mode", True)
    
    subject = f"Your Performance Report Card - Summer Training 2026 (Rank #{rank})"
    
    # Render beautiful email body
    email_body_html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #f4f5f7; padding: 20px; color: #333333;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; padding: 30px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); border: 1px solid #e1e4e8;">
            <h2 style="color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px;">Summer Training: ML & Agentic AI</h2>
            <p>Dear <strong>{student_name}</strong>,</p>
            <p>Congratulations on completing your assessments during the Summer Training program at <strong>Lloyd Institute of Engineering & Technology</strong>!</p>
            <p>Your performance report card has been successfully generated. Below is a summary of your results:</p>
            
            <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                <tr style="background-color: #f8fafc;">
                    <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Overall Percentage</td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #10b981; font-weight: bold;">{overall_pct:.1f}%</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Final Grade</td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #f59e0b; font-weight: bold;">{grade}</td>
                </tr>
                <tr style="background-color: #f8fafc;">
                    <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Program Rank</td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">#{rank}</td>
                </tr>
            </table>
            
            <p>We have attached your detailed **Individual Grade Card** (HTML format) to this email. You can open the attached file directly in any web browser to view your module-wise breakdown and percentile standing.</p>
            
            <p>Best regards,<br>
            <strong>Training Coordinator Team</strong><br>
            Lloyd Institute of Engineering & Technology</p>
            
            <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
            <p style="font-size: 11px; color: #64748b; text-align: center;">This is an automated performance update generated by the Agentic AI Training Pipeline.</p>
        </div>
    </body>
    </html>
    """
    
    if mock_mode:
        os.makedirs(OUTPUT_EMAILS_DIR, exist_ok=True)
        safe_email = student_email.replace('@', '_').replace('.', '_')
        mock_file_path = os.path.join(OUTPUT_EMAILS_DIR, f"{safe_email}_email.html")
        
        # Combine subject and body for the mock file output
        mock_content = f"""<!--
To: {student_email}
Subject: {subject}
Attachment: {grade_card_path}
-->
{email_body_html}
"""
        with open(mock_file_path, 'w', encoding='utf-8') as f:
            f.write(mock_content)
        return True, f"Mock email written to {mock_file_path}"
        
    else:
        # Real SMTP logic
        sender = email_settings.get("sender_email")
        password = email_settings.get("sender_password")
        smtp_server = email_settings.get("smtp_server", "smtp.gmail.com")
        smtp_port = email_settings.get("smtp_port", 587)
        
        msg = MIMEMultipart()
        msg['From'] = sender
        msg['To'] = student_email
        msg['Subject'] = subject
        
        msg.attach(MIMEText(email_body_html, 'html'))
        
        # Attach Grade Card
        if grade_card_path and os.path.exists(grade_card_path):
            with open(grade_card_path, "rb") as attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={os.path.basename(grade_card_path)}",
                )
                msg.attach(part)
                
        try:
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                if email_settings.get("use_tls", True):
                    server.starttls()
                server.login(sender, password)
                server.sendmail(sender, student_email, msg.as_string())
            return True, "Email sent successfully"
        except Exception as e:
            return False, f"Failed to send email: {e}"

def email_all_reports(df_students, grade_cards_dir):
    """Sends emails to all students with their attached grade cards."""
    success_count = 0
    errors = []
    
    for _, student in df_students.iterrows():
        email = student["Email"]
        name = student["Name"]
        pct = student["Cumulative_Pct"]
        grade = student["Grade"]
        rank = student["Rank"]
        
        safe_email = email.replace('@', '_').replace('.', '_')
        card_path = os.path.join(grade_cards_dir, f"{safe_email}.html")
        
        success, msg = send_performance_email(name, email, card_path, pct, grade, rank)
        if success:
            success_count += 1
        else:
            errors.append((email, msg))
            
    print(f"Emailed performance reports to {success_count} students.")
    if errors:
        print(f"Encountered {len(errors)} email sending errors:")
        for err_email, err_msg in errors:
            print(f" - {err_email}: {err_msg}")
            
    return success_count, errors
